name: solo_3
description: "Dog Breed Diary - fetches random dog images and saves favorites locally."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.0
  shared_preferences: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true